# Generated by Django 4.2.7 on 2023-11-27 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
    ]
