# Generated by Django 4.2.7 on 2023-11-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_delete_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
    ]
