# Generated by Django 4.2.7 on 2023-11-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="literaryformat",
            old_name="format",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="db.literaryformat",
            ),
        ),
    ]
