# Generated by Django 4.2.7 on 2023-11-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="books", to="db.author"),
        ),
    ]
